name: Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit_tests:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@master
        - uses: actions/setup-python@master
          with:
             python-version: '3.10'
             cache: 'pip'
        - name: Install poetry
          run: |
            python -m pip install --upgrade pip
            pip install --user poetry
        - name: Init environment
          run: |
            poetry update
            poetry install
        - name: Run tests
          run: pytest
